//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorArchicad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OperationNameTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationNameTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectorArchicad.Properties.OperationNameTemplates", typeof(OperationNameTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: Convert to native: {0}.
        /// </summary>
        internal static string ConvertToNative {
            get {
                return ResourceManager.GetString("ConvertToNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: Convert to Speckle: {0}.
        /// </summary>
        internal static string ConvertToSpeckle {
            get {
                return ResourceManager.GetString("ConvertToSpeckle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: HTTP command API: {0}.
        /// </summary>
        internal static string HttpCommandAPI {
            get {
                return ResourceManager.GetString("HttpCommandAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: HTTP command execute: {0}.
        /// </summary>
        internal static string HttpCommandExecute {
            get {
                return ResourceManager.GetString("HttpCommandExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: Mesh to native.
        /// </summary>
        internal static string MeshToNative {
            get {
                return ResourceManager.GetString("MeshToNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: Mesh to Speckle.
        /// </summary>
        internal static string MeshToSpeckle {
            get {
                return ResourceManager.GetString("MeshToSpeckle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: Receive From Server.
        /// </summary>
        internal static string ReceiveFromServer {
            get {
                return ResourceManager.GetString("ReceiveFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: Send To Server.
        /// </summary>
        internal static string SendToServer {
            get {
                return ResourceManager.GetString("SendToServer", resourceCulture);
            }
        }
    }
}
