---
name: Papercut
about: Small annoyances and issues that are not technically bugs
title: ''
labels: '✂️ paper-cut'
assignees: ''
---

# Describe the problem

> Include screenshots/gifs if you need to :)

