using DUI3.Utils;

namespace DUI3.Models;

public class ModelCard : DiscriminatedObject
{
  /// <summary>
  /// This is a unique id generated by the ui to make model cards easier to reference around.
  /// It's not the actual model (branch) id.
  /// </summary>
  public string Id { get; set; }
  public string ModelId { get; set; }
  public string ProjectId { get; set; }
  public string AccountId { get; set; }
  public string LastLocalUpdate { get; set; }
}

public class SenderModelCard : ModelCard
{
  public SendSettings SendSettings { get; set; }
  public SendFilter SendFilter { get; set; }
}

public class ReceiverModelCard : ModelCard
{
  // TODO: receive filter, receive settings, etc.
}
