using System.Collections.Generic;
using DUI3.Settings;
using DUI3.Utils;

namespace DUI3.Models;

public class ModelCard : DiscriminatedObject
{
  /// <summary>
  /// This is a unique id generated by the ui to make model cards easier to reference around.
  /// It's not the actual model (branch) id.
  /// </summary>
  public string Id { get; set; }

  /// <summary>
  /// Model id. FKA branch id.
  /// </summary>
  public string ModelId { get; set; }

  /// <summary>
  /// Project id. FKA stream id.
  /// </summary>
  public string ProjectId { get; set; }
  public string AccountId { get; set; }

  public List<CardSetting> Settings { get; set; }
}
