using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CefSharp;
using DesktopUI2.Models;
using DesktopUI2.ViewModels;
using Speckle.ConnectorRevit.Entry;
using Speckle.Core.Api;
using Speckle.Core.Credentials;

namespace Speckle.ConnectorRevit.UI
{

  public class RevitWebUIBindings : WebUI.WebUIBindings
  {
    public RevitWebUIBindings()
    {

    }

    public override async void ShowAccountsPopup()
    {
      throw new NotImplementedException();
    }

    // sample callback from web UI
    public override async void SendStream()
    {
      try
      {


        NotifyUi("show-notification", "Creating stream & sending...");

        string _fileName = WebUISpeckleRevitCommand.Bindings.GetFileName();
        var _fileStream = await CreateStream();

        var filters = WebUISpeckleRevitCommand.Bindings.GetSelectionFilters();
        var selection = WebUISpeckleRevitCommand.Bindings.GetSelectedObjects();

        _fileStream.Filter = filters.First(o => o.Slug == "all");
        _fileStream.CommitMessage = "Sent everything from DUI3";

        _fileStream.BranchName = "main";

        // set settings
        if (_fileStream.Settings == null || _fileStream.Settings.Count == 0)
        {
          var settings = WebUISpeckleRevitCommand.Bindings.GetSettings();
          _fileStream.Settings = settings;
        }
        var Id = await Task.Run(() => WebUISpeckleRevitCommand.Bindings.SendStream(_fileStream, new ProgressViewModel()));

        NotifyUi("show-notification", "Sent everything!");
      }
      catch (Exception ex)
      {
        Serilog.Log.Error(ex, ex.Message);
        NotifyUi("show-notification", "Error: " + ex.Message);
      }
    }

    private async Task<StreamState> CreateStream()
    {
      // get default account
      var account = AccountManager.GetDefaultAccount();
      var client = new Client(account);


      // create the stream
      string streamId = await client.StreamCreate(new StreamCreateInput { description = "Autogenerated Stream for QuickSend", name = "DUI3 Test Stream", isPublic = false });
      var newStream = await client.StreamGet(streamId);

      return new StreamState(account, newStream) { BranchName = "main" };


    }
  }
}
