using System;
using System.Diagnostics;
using Microsoft.CodeAnalysis;

namespace TestGenerator
{
  [Generator]
  public class HelloSourceGenerator : ISourceGenerator
  {
    public void Execute(GeneratorExecutionContext context)
    {
      // Find the main method
      var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

      // Build up the source code
      string source = $@"// <auto-generated/>
using System;

namespace hi
{{
    public static class hello
    {{
        static void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
    }}
}}
";

      // Add the source code to the compilation
      context.AddSource($"hello.g.cs", source);
    }

    public void Initialize(GeneratorInitializationContext context)
    {
      // No initialization required for this one
      //Debugger.Launch();
    }
  }
}
